'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Paquetes
    Public Property ID_PAQUETE As Integer
    Public Property NombrePaquete As String
    Public Property DescripcionPaquete As String
    Public Property UrlImagen As String
    Public Property Precio As Nullable(Of Decimal)
    Public Property Descuento As Nullable(Of Integer)
    Public Property PrecioFinal As Nullable(Of Decimal)
    Public Property Fecha As Nullable(Of Date)

End Class
