'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Venta
    Public Property ID_VENTA As Integer
    Public Property PaqueteVendido As Nullable(Of Integer)
    Public Property Total As Nullable(Of Decimal)
    Public Property FechaVenta As Nullable(Of Date)
    Public Property UsuarioComprador As Nullable(Of Integer)

End Class
