'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ViajeEstelarEntities2
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ViajeEstelarEntities2")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property Destino() As DbSet(Of Destino)
    Public Overridable Property Paquete() As DbSet(Of Paquete)
    Public Overridable Property Proveedor() As DbSet(Of Proveedor)
    Public Overridable Property Venta() As DbSet(Of Venta)
    Public Overridable Property Destinos() As DbSet(Of Destinos)
    Public Overridable Property Paquetes() As DbSet(Of Paquetes)

End Class
